package dev.samuuu.booktrackcompose.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Libro(

    @SerialName("id")
    val id: Int? = null, // Nullable because it's generated by the database
    @SerialName("created_at")
    val createdAt: String? = null, // Nullable because it's generated by the database
    @SerialName("titulo")
    val titulo: String,
    @SerialName("autor")
    val autor: String,
    @SerialName("valoracion")
    val valoracion: Int,
    @SerialName("estado")
    val estado: String, // Consider changing this to an Enum as well in the future
    @SerialName("imagenUrl")
    val imagenUrl: String,
    @SerialName("genero")
    val genero: Genero

)
